name: Tests
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.4"
      - uses: actions/checkout@v2
      - name: build
        run: go build ./vm/cmd/main.go

  test_vm:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 1
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.4"
      - uses: actions/checkout@v2

      - name: test VM
        run: go test -v ./vm/...
