name: Tests
on:
  pull_request:
  push:
    branches:
      - 0.34.19-lanslide-core

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - uses: actions/checkout@v4
      - run: go mod download
        shell: bash
      - name: build
        run: go build ./vm/cmd/main.go
        shell: bash

  test_vm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - uses: actions/checkout@v4
      - name: test VM
        run: go test -v ./vm/...
